#%RAML 1.0 DataType
properties:
  statuscode:
    type: string
    example: '404'
  errorType: 
    type: string
    example:
      'not found'
  errorDescription: 
    type: string
    example:
      'method not found' 